### PR TITLE
fix some errors, replace test files with valid files

### PR DESCRIPTION
**Pull request by mfdeveloper508**
- fix check of valid format in command line
- remove Block Descriptor Word of trailer record
- update checker of pack, variable record
- Does not allow a value of 0 for current balance and highest credit on v0.3.1
- replace valid test files

### CODE REVIEW

**Review by wadearnold — APPROVED** [review]

**Comment by wadearnold** [comment]
Can you fix this build failure and I will get it merged. 
pkg:golang/github.com/dgrijalva/jwt-go@3.2.0

**Comment by adamdecaf** [comment]
Taking a look at the build failure.

**Comment by adamdecaf** [comment]
I rebased off origin/master after fixing the nancy checks. There looks to be an error still when running locally.

**Comment by mfdeveloper508** [comment]
yes, there is another issue too. will fix soon

**Comment by adamdecaf** [comment]
Back to a successful build!

**Comment by adamdecaf** [comment]
@mfdeveloper508 Is this ready to merge?

**Comment by mfdeveloper508** [comment]
sure, we can merge into master

**Comment by mfdeveloper508** [comment]
thanks

**Pull request merged**
