### PR TITLE
CurrentBalance validator fails

### PR DESCRIPTION
**Pull request by mfdeveloper508**
https://github.com/moov-io/metro2/issues/128

spec's configuration is incorrect

### CODE REVIEW

**Comment by adamdecaf** [comment]
Are we required to upgrade openapi-generator versions in order to fix this issue? That upgrade includes a lot of breaking changes.

**Comment by adamdecaf** [comment]
Can we fix the issue and release v0.5.2 without the openapi-generator upgrade? 

Then we can release v0.6.0 with the openapi-generator updated.

**Comment by mfdeveloper508** [comment]
yes, this is possible 
the issue is not openapi issue

**Comment by mfdeveloper508** [comment]
https://github.com/moov-io/metro2/pull/132

**Pull request closed without merging**
