### PR TITLE
feat: add StringWithConcurrency function

### PR DESCRIPTION
**Pull request by mdross95**
Proposal for adding `StringWithConcurrency` function to `file_instance`.

When testing metro2 file generation with a large amount of segments with moov metro2, I noticed that the `String()` function in `file_instance` can take a decent amount of time (i.e. ~15 minutes on my machine for close to ~200k segments). 

To alleviate this, I implemented a simple `StringWithConcurrency` function in our fork that takes in a desired # of concurrent goroutines, splits up the base segment processing into that amount of chunks, processes them in parallel, and merges them at the end.

In my testing, leveraging this function has allowed us to reduce the `String()` generation time by over tenfold.

We are now using this function in our fork for furnishment process - I figured I would open a PR if moov thinks it is valuable to the main repo. Please let me know what you think - thanks!

### CODE REVIEW

**Review by adamdecaf — APPROVED** [review]
This makes sense. Thanks!

**Comment by adamdecaf** [comment]
I'm thinking that `ConcurrentString(isNewline, goroutines)` sounds better. Thoughts?

**Comment by adamdecaf** [comment]
Also, is there a reason we don't default this as runtime.NumCPU() ?

**Comment by mdross95** [comment]
`ConcurrentString` works for me, and sure, we could default it to that in `String()` instead of sending `1` 👍

**Comment by adamdecaf** [comment]
https://github.com/moov-io/metro2/commit/eb9fc666e59d5fc315e35fa04c07d4fbf52874c0

**Pull request merged**
